### ISSUE TITLE
Изменить RowKey, чтобы последние записи оказвались "сверху"

### ISSUE THREAD

**Issue by justdmitry** [iflight/RequestLogger.AzureTable#1]
Для удобного выбора последних записей можно воспользоваться рекомендациями MS и сделать RowKey таким, чтобы при сортировке по возрастанию последние записи оказывались первыми - [Log tail pattern](https://azure.microsoft.com/en-us/documentation/articles/storage-table-design-guide/#log-tail-pattern)

Это потребует хранения "привычных" даты и времени в отдельном поле, но это допустимая "цена".

**Comment by iflight** [comment]
исправлено в  e7543fe
