### ISSUE TITLE
Подключение Middleware блокирует чтение Request.Body

### ISSUE THREAD

**Issue by justdmitry** [iflight/RequestLogger.AzureTable#2]
При подключении Middleware для логгирования входящих соединений теряется возможность чтения содержимого `Request.Body` - стрим оказывается пустым.

**Comment by justdmitry** [comment]
`string requestBody = new StreamReader(context.Request.Body).ReadToEnd();`

Думаю здесь тоже надо подменять на новый MemoryStream.

**Comment by iflight** [comment]
исправлено в bd869a0
