### ISSUE TITLE
Если не указать interval, то возникает ошибка - DI-контейнер не может создать экземпляр

### ISSUE THREAD

**Issue by justdmitry** [iflight/RequestLogger.AzureTable#5]
Если оставить "старый" вариант конфигурирования в `Statup.Configure` (без нового параметра `interval`):

```
app.UseRequestLogger(
    @"UseDevelopmentStorage=true;", 
    "AzureLoggerDemo", 
    new string[] { "demo" });
```

То при старте приложения возникает ошибка:

> An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Http.Abstractions.dll
> 
> Additional information: A suitable constructor for type 'iflight.RequestLogger.AzureTable.RequestLoggerMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

**Comment by iflight** [comment]
с 0.3 используется RequestLoggerOptions для передачи параметров.
